"""add source_job_id to jobs

Revision ID: 3389b7c3adc4
Revises: 965fd433655f
Create Date: 2026-08-22 17:09:12.855266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3389b7c3adc4'
down_revision: Union[str, Sequence[str], None] = '965fd433655f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('source_job_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_jobs_source_job_id'), 'jobs', ['source_job_id'], unique=False)
    op.create_unique_constraint('uq_jobs_source_job_id', 'jobs', ['source', 'source_job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_source_job_id', 'jobs', type_='unique')
    op.drop_index(op.f('ix_jobs_source_job_id'), table_name='jobs')
    op.drop_column('jobs', 'source_job_id')
    # ### end Alembic commands ###
