"""add predicted subcategory to jobs

Revision ID: 78a7e166890e
Revises: e08152d5e10c
Create Date: 2026-08-26 22:05:53.488693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a7e166890e'
down_revision: Union[str, Sequence[str], None] = 'e08152d5e10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('predicted_subcategory', sa.String(length=60), nullable=True))
    op.add_column('jobs', sa.Column('classifier_confidence', sa.Float(), nullable=True))
    op.create_index(op.f('ix_jobs_predicted_subcategory'), 'jobs', ['predicted_subcategory'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_predicted_subcategory'), table_name='jobs')
    op.drop_column('jobs', 'classifier_confidence')
    op.drop_column('jobs', 'predicted_subcategory')
    # ### end Alembic commands ###
