"""add job history columns

Revision ID: e08152d5e10c
Revises: 3389b7c3adc4
Create Date: 2026-08-22 17:27:44.355118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08152d5e10c'
down_revision: Union[str, Sequence[str], None] = '3389b7c3adc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('first_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('jobs', sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('jobs', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.create_index(op.f('ix_jobs_expiry_date'), 'jobs', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_jobs_first_seen'), 'jobs', ['first_seen'], unique=False)
    op.create_index(op.f('ix_jobs_is_active'), 'jobs', ['is_active'], unique=False)
    op.create_index(op.f('ix_jobs_last_seen'), 'jobs', ['last_seen'], unique=False)
    # ### end Alembic commands ###

    # Backfill for jobs that were already scraped before these columns existed.
    # Adding the columns filled them with the current timestamp, which would
    # lose the real first seen time, so copy scraped_at across instead.
    # expiry_date stays null and is_active stays true until the next scrape run
    # supplies the real closing date.
    op.execute("UPDATE jobs SET first_seen = scraped_at, last_seen = scraped_at")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_last_seen'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_active'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_first_seen'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_expiry_date'), table_name='jobs')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'expiry_date')
    op.drop_column('jobs', 'last_seen')
    op.drop_column('jobs', 'first_seen')
    # ### end Alembic commands ###
