"""add forecast trend columns

Revision ID: e7d1ed479649
Revises: 78a7e166890e
Create Date: 2026-08-27 12:50:50.140473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d1ed479649'
down_revision: Union[str, Sequence[str], None] = '78a7e166890e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts', sa.Column('current_demand', sa.Float(), nullable=True))
    op.add_column('forecasts', sa.Column('pct_change', sa.Float(), nullable=True))
    op.add_column('forecasts', sa.Column('trend', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_forecasts_trend'), 'forecasts', ['trend'], unique=False)
    op.create_unique_constraint('uq_forecasts_sub_horizon_model', 'forecasts', ['subcategory', 'horizon_months', 'model_version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_forecasts_sub_horizon_model', 'forecasts', type_='unique')
    op.drop_index(op.f('ix_forecasts_trend'), table_name='forecasts')
    op.drop_column('forecasts', 'trend')
    op.drop_column('forecasts', 'pct_change')
    op.drop_column('forecasts', 'current_demand')
    # ### end Alembic commands ###
